import 'dotenv/config';
import {
    getExperience,
    getCareerPath
} from './utils';
import { topicsAgent } from './topics/topics';
import { enhanceAgent } from './enhance/enhance';
import type { resumeLanguage } from '@resume-builder/shared';


const testExp = await getExperience(12)
const testCareer = await getCareerPath(7)
console.log(testExp)
console.log(testCareer)


export async function invokeEnhanceAgent() {
    const result = await enhanceAgent.invoke({
        expId: testExp.id
    })
    return result
}

const result = await invokeEnhanceAgent()
console.dir(result, { depth: null, colors: true });


// To do:

// Implement data base saving capabilities for enhanced experience description 
// Decide how to proceed with topics Agent. Sequence of the topic, choose the best 3 or less and push all others into one bullet point. 


// Implement reasoning system to create an AI enhanced version of Experience 

// Add types for db interactions
// The Agent is meant to generate topics for one experience per career path. 
// Career Path
// -Exp1 -> has a button to generate topics
//  - Topic 1   <- Generated by the first Agent run
//  - Topic 2   <- Generated by the first Agent run
//  - Topci 3   <- Generated by the first Agent run
// -Exp2 -> has a button to generate topics
//  - Topic 1   <- Generated by the second Agent run
//  - Topic 2   <- Generated by the second Agent run
//  - Topci 3   <- Generated by the second Agent run
// -Exp3 -> has a button to generate topics
//  - Topic 1   <- Generated by the trhird Agent run
//  - Topic 2   <- Generated by the trhird Agent run
//  - Topci 3   <- Generated by the trhird Agent run
//  


// based on the enhanced experience and career path, to create a list.

// How to create a single topic:
// Take each topic separatley from enhanced experience
// Single topic from exp + career path description -> Solid Topic proposition
// Each Exp for 


// Topics agent:
// Gets all topics from enhanced exp
// 
