import 'dotenv/config';
import {
    getExperience,
    getCareerPath
} from './utils';
import { topicsAgent } from './topics/topics';
import { enhanceAgent } from './enhance/enhance';
import type { resumeLanguage } from '@resume-builder/shared';


const testExp = await getExperience(11)
const testCareer = await getCareerPath(7)
console.log(testExp)
console.log(testCareer)


async function invokeEnhanceAgent() {
    const result = await enhanceAgent.invoke({
        userSummary: testExp.experience.description,
        workstreams: [],
        writerRedefinedTopics: [],
        expId: testExp.id,
        userId: testExp.user_id,
        resumeLang: testExp.resume_lang as resumeLanguage,
        operationStatus: 'init'
    })
    return result
}

const result = await invokeEnhanceAgent()
console.dir(result, { depth: null, colors: true });


// To do:

// Implement data base saving capabilities for enhanced experience description 
// Decide how to proceed with topics Agent. Sequence of the topic, choose the best 3 or less and push all others into one bullet point. 


// Implement reasoning system to create an AI enhanced version of Experience 

// Add types for db interactions
// The Agent is meant to generate topics for one experience per career path. 
// Career Path
// -Exp1 -> has a button to generate topics
//  - Topic 1   <- Generated by the first Agent run
//  - Topic 2   <- Generated by the first Agent run
//  - Topci 3   <- Generated by the first Agent run
// -Exp2 -> has a button to generate topics
//  - Topic 1   <- Generated by the second Agent run
//  - Topic 2   <- Generated by the second Agent run
//  - Topci 3   <- Generated by the second Agent run
// -Exp3 -> has a button to generate topics
//  - Topic 1   <- Generated by the trhird Agent run
//  - Topic 2   <- Generated by the trhird Agent run
//  - Topci 3   <- Generated by the trhird Agent run
//  

// what if the user descriptions are not enough to bring this idea to live?

// Is there any sense to create... yes. It needs to be redefined. I will cerate custom prompt workflows to ensure that it works as intended. And I know that this is possible with low cost. 

